
server:
  port: ${RESOURCE_SRV_PORT}

logging:
  level:
    org.springframework.security: DEBUG

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_LOGIN}
    password: ${DB_PW}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_URL}