
server:
  port: 8090

logging:
  level:
    org.springframework.security: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/project-guild
    username: postgres
    password: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000